<p>
  1. Upon submission of the appropriate insurance or surety bond application and such other information required by TBE or any insurer or surety with whom TBE is considering placing the insurance or bond requested: a. TBE may, if it considers it appropriate to do so, provide the Producer with a quote for such insurance or bond. b. Producer acknowledges that the coverage or terms and conditions offered in a quote provided by TBE may vary from those requested on the application submitted by Producer. Producer agrees to review any quote carefully with the applicant, including explaining the coverage and relevant termsandconditions.Producerisresponsibletodiscloseallapplicable forms,exclusions,endorsements, riders, warrantees, and fees, to its client. c. If the applicant elects to purchase the insurance or bond offered,TBEwillbindcoverageorissuethebondasagreedorotherwise procuretheinsuranceorbond ifsuchinsuranceorbondisstillofferedonthesametermsandconditions bytheinsurerorsuretyfrom whom the quote was obtained. d. TBE may decline, in its sole and unfettered discretion, to submit the application to any insurer or surety if TBE considers it inappropriate to do so. e. Producer shall have no righttoasubmissiontoanyparticularinsurerorsurety,whichshallbeselectedby TBE.
</p>
<p>
  2. Producer shall act in the exclusive capacity of an insurance producer1 in its business dealings with TBE subject to the terms and conditions of this Agreement. a. Producer shall obtain a written disclosure, when required by law, signed by the applicant, indicating that the Producer is transacting on the applicant’s behalf, a description of insurance services that Producer will perform for the applicant, the amount of all fees that Producer may charge the applicant, and the compensation Producer may receive for any transaction made pursuant to this Agreement. b. Producer shall represent only the applicant for insurance or surety. <strong>c. PRODUCER HAS NO AUTHORITY TO SPEAK ON BEHALF OF OR BIND ANY COVERAGE OR ISSUE ANY BOND, BIND OR SIGN ANY POLICY OR ENDORSEMENT ON NEW OR RENEWAL BUSINESS OR RENEW ANY BOND, OR IN ANY OTHER WAY BIND OR INCUR ANY OBLIGATION ON BEHALF OF TBE OR ANY INSURER OR SURETY FROM WHOM TBE OBTAINS OR REQUESTS ANY INSURANCE OR BOND FOR PRODUCER’SCLIENT.PRODUCER SHALLNOTHOLDITSELF,HERSELF,ORHIMSELF OUT TO HAVE ANY SUCH POWER OR AUTHORITY. PRODUCER IS NOT AN AGENT OR REPRESENTATIVEOFTBEORANYINSURERORSURETY.</strong>d.Nocoverageshall attachorbe bound or any bond issued until TBE has provided Producer with written confirmation. e. TBE has been provided with underwriting rules and requirements by its insurers and sureties and is required to comply with all aspects of the insurers’ or sureties’ underwriting rules and requirements established by the insurers or sureties for TBE which may act as the insurers’ or sureties’ general agent. All information submitted by Producer to TBE is subject to TBE review and approval. Producer represents to TBE that all information submitted in any electronic or written medium is complete and fully complies with the underwriting rules and requirements provided by TBE which are necessary to permit TBE to bind coverage or issue bonds with its insurers or sureties. TBE shall review and will reject any submitted information received by any electronic or written medium from Producer which is contrary to the underwriting rules and requirements of TBE’s insurers or sureties. For the purposes of this Agreement, Producer, in addition to Producer services normally rendered to Producer’s client, is exclusively limited to collection and transmission of premium or return premium funds and delivery of policies and other documents evidencing insurance coverage or bond issuance. f. In the event of cancellation or non-renewal of any policy or bond obtained through TBE, the Producer shall not represent to the client or any other person that it is authorized to, and will not, accept any premium payment from the client or reinstate coverage or a bond without the prior written consent of TBE.
</p>
<p>
  3. Producer has no authority to, and shall not, a. amend any coverage or provisions under any policy or any terms and conditions of any bond obtained through TBE; b. release premium indications from any “Price Indicators” or price any bonds without prior written approval by TBE; c. submit an application for insurance or surety bond for a customer that Producer does not represent.
</p>
<p>
  4. In connection with an application for insurance or surety bond through TBE, Producer: a. represents and warrants that to the best of Producer’s knowledge after a diligent investigation, all information contained on an application and all other information submitted to TBE is complete and accurate and that no statement is, in the context of the known facts, misleading or only partially truthful; b. shall promptly provide to TBE all information and documentation necessary to enable TBE to obtain the requested insurance or surety bond; c. understands that TBE may conduct a review of an applicant’s personal credit history and that Producer is required to obtain authorization from the applicant, as required by law, for TBE to obtain the applicant’s credit report from any of the major credit reporting agencies; d. shall maintain, and, if requested by TBE, make available or provide to TBE any and all documentation in Producer’s files reflecting the applicant’s selection of applicable coverage, limits, deductible, and selection of any other terms or conditions of insurance or surety bond and any and all statements or documentation indicating insurability or qualification for bonding, including, but not limited to, accurately completed and signed original applications; and e. make sure that the procedures above are understood and followed by all of the Producer’s employees responsible for representing any applicant or insured in dealing with TBE.
</p>
<p>
  5. Producer is an independent insurance producer and not an employee of TBE. Nothing in this Agreement shall be interpreted as creating an employee/employer, partnership, or joint venture relationship between TBE and Producer. Producer shall not represent to any person or entity that he or she is an employee, partner, or joint venturer of TBE.
</p>
<p>
  6. Producer shall be fully responsible to TBE for all premiums on insurance or surety bonds whether original, renewal, installment, audit or other, on business placed by Producer through TBE, and TBE shall not be responsible for premiums advanced by Producer. a. Producer guarantees payment to TBE of all earned premiums on insurance or surety bonds placed through TBE. b. No binder, policy, certificate, or cover note may be cancelled flat after the inception date of coverage or term of bond without the written consent of TBE. c. Producer assumes full responsibility for the payment of all premiums on binder, policies, certificates or cover notes issued at the request of the Producer. d. TBE may establish or change at any time procedures for paying premium due on insurance or bonds issued through TBE, including, without limitation, electronic funds transfers or installment payments of premiums. e. Any separate bill provided by TBE for any insurance or bond shall supersede any itemization provided to the Producer that includes the separately invoiced payment due.
</p>
<p>
  7. Whenever a policy or binder is issued by TBE, premium shall be deemed to be earned, unless it is returned with evidence satisfactory to TBE that such policy or binder did not result in a valid and effective policy or contract between the applicant and the insurer. For annual or multi-year surety bonds that are cancellable and provisions in the applicable insurance company rate filings do not deem the premium to be fully-earned, premium is deemed to be earned subject to a pro rata schedule over the term of the surety. For all other bonds, the premium is fully earned upon issuance.
</p>
<p>
  8. If a policy or policy’s premium has been financed by an insured through a third party, the Producer, on its, her, or his own behalf and on behalf of the applicant, agrees that the premium financed shall be payable and immediately remitted directly to TBE. In conjunction with a quoted bond or policy, TBE, at its sole discretion, may offer the policyholder or bond principal to make payments in installments. If such an arrangement has been made, the policyholder or bond principal shall pay TBE or the Producer the down payment including an installment fee at the time of issuance and installment payments including an installment fee will be automatically charged to the credit or debit card provided by the policyholder or bond principal on each due date. If the Producer collects the down payment at the time the policy or bond is issued, the Producer agrees to remit the down payment less the commission to TBE within 30 calendar days. If the policyholder or bond principal fails to make an installment payment by the agreed upon payment schedule, the policy or bond will be cancelled immediately. TBE reserves the right to retain any unearned premium in excess of amounts due to TBE to defray the costs associated with collection and cancellation. The Producer agrees to remit to TBE immediately any unearned commission collected but not yet earned. TBE will determine the unearned commission calculation based on the cancellation provisions of the policy or bond.
</p>
<p>
  9. With respect to fees or commissions due to TBE; a. All such fees or commissions are fully earned upon issuance by TBE of a certificate, binder or confirmation of coverage; b. Producer shall promptly remit to TBE all fees required for such insurance or surety bond; c. Producer shall be liable to TBE for the full amount of premium and applicable state taxes, less commission, on every insurance contract or surety bond placed through TBE for Producer. Except for bonds in which TBE deems premium due immediately, Producer will collect, account for, and pay premiums due on all insurance or surety bonds ordered from or obtained by Producer through TBE and submit them to TBE no later than thirty (30) days after the end of the month for which the accounting is rendered. e. Producer will pay to TBE all earned premium on each policyplacedthrough TBEevenifProducerdoesnotcollectapremiumfromthepolicyholderorprincipal.
</p>
<p>
  10. Producer shall be fully responsible for ensuring that all documentation, including but not limited to, binders, policies, certificates, bonds, and cover notes are properly delivered to insured or principal and filed with an obligee, if required, pursuant to any applicable regulatory requirements. Producer shall be fully responsible for notifying TBE of any special delivery requirements if they have elected for TBE to assist them in delivering documentation to the insured or principal and obligee.
</p>
<p>
  11. This agreement shall continue in force without interruption until terminated by either party. a. This Agreement shall terminate: (i) Automatically on the date any public authority suspends or declines to renew the Producer’s license or certificate of authority; or (ii) Immediately upon one party giving written notice to the other party in the event of abandonment, fraud, or gross and willful negligence or misconduct on the part of the other party; or (iii) Immediately if either party is: unable to pay its debts as they mature; makes an assignment for the benefit of creditors; commences dissolution proceedings; a receiver or liquidator is appointed over all or substantially all of its property; or insolvency, bankruptcy, reorganization, arrangement or similar proceedings are instituted by or against either party; or (iv) Upon any party hereto giving the other party thirty (30) days advance written notice setting forth the effective termination date (or longer if required by applicable state law). b. TBE may, on ten (10) days written notice to Producer, change the commission rate of Producer then currently in effect. c. Any amounts due and owing to one party by the other party at the time of termination as a result of business written prior to the effective date of termination will be paid or settled promptly upon such termination. d. Upon termination, Producer agrees to return promptly to TBE any written materials and supplies furnished by TBE. e. TBE may suspend Producer’s ability to access the TBE website and submission systems provided by TBE. Producer shall have no right of access to the TBE website and submission systems provided by TBE after termination of this Agreement.
</p>
<p>
  12. Producer shall, upon request by TBE, pay or repay to TBE; a. any taxes payable by TBE as the result of any contracts of insurance or surety bonds placed with an insurer or surety by TBE that are not recoverable; b. any unearned commission and any debit balance, however created, which is owed to TBE; c. TBE reserves the right to retain any funds otherwise payable to the Producer at any time at which the Producer is indebted to TBE.
</p>
<p>
  13. Any extension of credit by Producer to its, her, or his client is solely at Producer’s own risk. Producer shall pay to TBE all amounts due to TBE whether or not these funds have been collected from the Producer’s client or anyone else who owes it.
</p>
<p>
  14. Producer acknowledges and understands that TBE shall receive commissions from the insurer or surety and in some instances may receive other consideration, including, but not limited to, profit sharing payments or contingent commission, where permissible by law.
</p>
<p>
  15. In the event of a claim under a policy or bond obtained through TBE, Producer will promptly: a. report to TBE any such claim and related information; and b. obtain any information from the insured client or principal and obligee required by the insurer, surety or TBE.
</p>
<p>
  16. Producer will maintain Errors and Omissions Insurance coverage at all times with coverage limits of at least $1,000,000 per claim. Producer shall provide to TBE proof of the required insurance at the request of TBE. Producer shall promptly notify TBE in advance if coverage is discontinued, reduced, materially changed, or cancelled and shall procure from Producer’s insurer an obligation to give TBE prompt written prior notice of any such discontinuation, reduction, amendment or cancellation.
</p>
<p>
  17. By entering your Taxpayer Identification Number (TIN), Producer and its officers are certifying the numbers entered are the correct taxpayer identification numbers, Producer is not subject to backup withholding and Producer is a U.S. Citizen or other U.S. person. The TIN must match the name given as "Legal Name". For individuals, this is your social security number (SSN) and for any other entity type, this is your employer identification number (EIN).
</p>
<p>
  18. By signing, Producer and its officers are providing ‘written instructions’ to TBE under the Fair Credit Reporting Act authorizing TBE to obtain information from their personal credit profile or other information from a credit reporting agency. Producer authorizes TBE to obtain such information solely to conduct a pre-qualification for credit. This is not an application for credit and will not affect your credit score.
</p>
<p>
  19. Producer represents and warrants that Producer currently holds all licenses necessary to perform the services described in this Agreement from each state in which it does business, has no legal restrictions, by law, agreement or otherwise, prohibiting or restricting Producer’s performance under this Agreement, and will: a. maintain all required licenses during the term of this Agreement; b. promptly notify TBE within five (5) business days of any suspension, revocation, or other adverse action by any licensing agency with respect to Producer’s license and immediately return any commissions or fees paid by TBE to Producer that Producer is not legally entitled to collect; c. Provide, upon request of TBE, evidence of compliancewith allapplicablelicensinglaws,regulations,orrequirementsinanystateinwhichProducer doesbusinessor resides.
</p>
<p>
  20. This Agreement and Producer’s rights hereunder are non-exclusive and do not limit the rights of TBE to enter into any similar agreements with other Producers or agents at any time. This Agreement contains no guaranty of dollar volume or geographic exclusive location to Producer.
</p>
<p>
  21. TBE shall indemnify and hold Producer harmless from any and all damages, claims, costs, including reasonable attorney fees, and other liabilities of any nature or kind arising out of, or based on, the performance by TBE of its obligations hereunder.
</p>
<p>
  22. Producer shall indemnify and hold TBE and its officers, directors, employees, agents and representatives, harmless from any and all damages, claims, costs, including reasonable attorney fees, and other liabilities of any nature or kind based on, or arising out of, the performance by Producer of its, his, or her obligations hereunder.
</p>
<p>
  23. The parties may communicate with each other by mail, facsimile, or electronically.
</p>
<p>
  24. Producer acknowledges that TBE has and will have valuable Confidential Information (as defined below). a. Producer will, as a result of this Agreement, have access to, or might otherwise become acquainted with such Confidential Information. b. Producer shall not, directly or indirectly, give, sell, transfer or in any way communicate or divulge to any person or entity, or use for Producer’s own benefit or the benefit of any other person or entity (except TBE) any Confidential Information without the express prior written consent of TBE. c. The term “Confidential Information” means any and all information relating to TBE not known by, or available in ordinary circumstances to, the public generally including, without limitation, the following: i. passwords; ii. TBE marketing techniques and materials; iii. the terms of TBE business relationships with insurers iv. any lists of clients, prospective clients, referral sources and sales agents maintained by TBE; v. the terms of business relationships between TBE and sales agents; vi. premium charges and other terms and conditions for insurance or surety coverage provided through TBE; vii. TBE’s underwriting practices; viii. technical information concerning TBE’s products and services, including product know-how, formulas, designs, diagrams, rates, software code and design, test results, processes, inventions, research projects and product development, technical memoranda and correspondences, website development and developers; ix. information concerning TBE’s business, including cost information, profits, sales information, accounting and unpublished financial information, business plans, markets and marketing methods, service techniques and methods, insureds or principals lists and insured or principal’s information, purchasing techniques, insurance carrier lists and information, program loss data and experience, producer lists and producer information, advertising strategies, training and instruction techniques, opportunities, associations, and processing methods and techniques; and x. financial information concerning TBE. d. In the event of termination of this Agreement, provided the Producer has promptly accounted for and paid over premiums for which he may be liable to TBE and the Agreement has not been terminated for cause, the Producer's records, use, and control of expirations shall remain the property of the Producer and be left in the Producer’s undisputed possession. Otherwise, the records, use, and control of expirations shall be vested and belong to TBE.
</p>
<p>
  25. Any breach of the immediately preceding paragraph (paragraph number 24) will cause irreparable harm for which TBE will have no plain, speedy or adequate legal remedy, and TBE shall be entitled to an injunction and temporary restraining order prohibiting such breaches by Producer. Nothing in this Agreement shall be construed as preventing TBE from pursuing any remedy at law or in equity for any breach or threatened breach.
</p>
<p>
  26. If a conflict regarding an individual account results in the replacement of a producer pursuant to a Broker of Record Letter (“BOR”), the incumbent producer and the new producer of record shall resolve such conflict and provide in writing to TBE the following: a. The effective date of the change in the producer of record; b. Provisions for premium collection; and c. Provisions for the repayment of commissions, including the refund of return commissions.
</p>
<p>
  27. If TBE is not notified of the resolution of any BOR issues by the incumbent producer and the new producer within ten (10) days, TBE reserves the right to resolve any issues related to the BOR in its sole discretion, and its decision shall be final and binding upon all parties.
</p>
<p>
  28. The Producer shall comply with TBE’s policies and procedures governing the designation of producers of record.
</p>
<p>
  29. Producer shall not utilize the TBE name, logo, trademark or other identifying information of TBE, including any products offered by TBE, in the conduct of its business without the prior written consent of TBE. In addition, Producer must obtain written permission from TBE to use any marketing materials concerning TBE’s products produced by Producer, TBE, or any other.
</p>
<p>
  30. Any information of any kind about or concerning any client, customer, insured, claimant, or other person that is subject to any state, local, or federal law requiring such information to be kept confidential shall be kept confidential by Producer. A. Producer shall notify TBE of any such information when and if conveyed to TBE. B. Producer shall not disclose any such information to any third person unless authorized by such client, customer, insured, claimant, or other person or compelled by a governmental agency of an order of a court. C. Producer has or will promptly adopt a privacy policy consistent with applicable federal, state and local laws and the requirements of any insurer with whom TBE does business.
</p>
<p>
  31. If Producer chooses to use the e-signature feature option provided by TBE to allow electronic signatures (“the E-Sign Option”), Producer is agreeing to conduct business transactions with electronic documents and signatures instead of paper-based documents and signatures. The term “electronic signature” means an electronic sound, symbol, or process, attached to or logically associated with a contract or other record and executed or adopted by a person with the intent to sign the record. Producer acknowledges and agrees that TBE may utilize the services of a third party (“Vendor”) to help facilitate the use of the E-Sign Option. Producer is under no obligation to transact business electronically. To withdraw Producer’s consent to conduct electronic transactions, simply stop using the E-Sign Option and contact the sending party to explore other options.
</p>
<p>
  32. Producer may read and sign each document on a case-by-case basis. Each decision to view or sign a document electronically does not affect the legal effect of any transactions already completed using either electronic or paper-based documents and signatures. Producer hereby agrees to read every document before electronically signing it. Producer also agrees to communicate all issues regarding the content of a document directly with the sending party. Finally, Producer agrees to notify the sending parties and the Vendor of any change in your e-mail address in order to prevent interruptions to Producer’s communications.
</p>
<p>
  33. Producer acknowledges and understands that electronic signatures are legally binding in the United States and other countries. Producer also understands that printed copies of electronic documents are not considered legal originals, but rather copies of the original documents signed via the E-Sign Option. There are no additional fees for printing or exporting electronic documents or signatures and Producer may obtain a paper copy of any document signed via the E-Sign Option by providing a written request to TBE.
</p>
<p>
  34. Use of the E-Sign Option requires a standards-compliant web-browser which supports the HTTPS protocol, HTML, and cookies. Many documents and communications will include PDF and Word attachments requiring additional software.
</p>
<p>
  35. Electronic signatures are void where prohibited by law. The United States Electronic Signatures in Global and National Commerce Act (the “Act”) preserves the legal effect, validity, and enforceability of signatures and contracts relating to electronic transactions and electronic signatures used in the formation of certain electronic contracts. However, as further described in the Act, the Act does not apply to certain contracts and records governed by statutes and regulations such as those related to probate and domestic law matters; state commercial law; consumer law covering utility services, real property defaults and foreclosures, and insurance benefits; product recall notices; and hazardous materials papers.
</p>
<p>
  36. This Agreement or any rights or obligations hereunder may not be assigned or otherwise transferred by Producer, but may be assigned or transferred by TBE at any time and without prior notice to Producer or Producer’s consent. Written notification to Producer of an assignment or transfer by TBE of its rights hereunder shall, without further act or notice, relieve TBE of any and all obligations under this Agreement. Any attempted assignment of rights or obligations under this Agreement by Producer shall be void and unenforceable.
</p>
<p>
  37. Any modification or amendment of this Agreement must be in writing and signed by all parties.
</p>
<p>
  38. Any notice required by this Agreement shall be given to the parties at the addresses, telephone or facsimile numbers, or email addresses provided to each other or on their website, advertising literature or business stationery.
</p>
<p>
  39. If any dispute arises involving the interpretation or enforcement of any provision of this Agreement, the prevailing party shall be entitled to recover reasonable attorney fees, including court costs and fees, from the other party.
</p>
<p>
  40. This Agreement is the sole agreement between the parties, contains the entire agreement and terms between the parties, and supersedes other agreements related to the subject matter of this Agreement.
</p>
<p>
  41. This Agreement shall be governed by the laws of the state of North Carolina without giving effect to its conflicts of law provisions. Both parties hereby agree that any such action or proceeding arising out of, or related in any way to, this agreement shall be brought solely in a court of competent jurisdiction sitting in Charlotte, North Carolina. Both parties hereby irrevocably and unconditionally consent to the jurisdiction of any such court and the Producer hereby irrevocably and unconditionally waives any defense of an inconvenient forum to the maintenance of, or defense to, any action or proceeding in any such court, any objection to venue with respect to any such action or proceeding, or any right of jurisdiction on account of the place of residence or domicile of any party hereto. Both parties hereby irrevocably and unconditionally waive the right to a jury trial in connection with any claim arising out of or relating to this Agreement.
</p>
<p>
  42. This Agreement is entered into in the city of Charlotte, State of North Carolina, which is where TBE’s headquarters is located. This Agreement shall be performed primarily in the city of Charlotte, State of North Carolina.
</p>
<p>
  43. The failure to exercise any right provided in this Agreement shall not be a waiver of prior or subsequent rights.
</p>
<p>
  44. If any provision in this Agreement is held to be unreasonable, invalid, void, or unenforceable, then this Agreement will be deemed amended to provide for the modification of the unreasonable, invalid, void, or unenforceable provision to the extent that the court or arbitrator finds reasonable, and the remaining provisions of this Agreement will continue in full force without being impaired or invalidated in any way.
</p>
<p>
  45. The Producer’s obligations and the rights of TBE set forth in this Agreement shall survive termination of this Agreement. The rights and remedies provided for in this Agreement shall be cumulative and not exclusive and shall be in addition to any other remedies which the parties may have under this Agreement or otherwise.
</p>
<p>
  46. This Agreement applies to current in-force policies or bonds as of the date hereof and all future policies or bonds which may be placed by TBE for Producer.
</p>
<p>
  47. This Agreement may be executed in two or more counterparts, each of which shall be deemed an original, but all of which together shall constitute one and the same instrument. An executed copy of this Agreement that is delivered by a party electronically shall be binding on that party as if it were an original.
</p>
